/*
 *  Copyright OpenSearch Contributors
 *  SPDX-License-Identifier: Apache-2.0
 */

rootProject.name = 'opensearch-knn'

include ":engines"
include ":engines:faiss"
include ":engines:lucene"
include ":engines:nmslib"
include ":enginelib"
include ":plugins"
include ":plugins:bruteforce"
include ":qa"
include ":qa:rolling-upgrade"
include ":qa:restart-upgrade"
include ":remote-index-build-client"

