import org.opensearch.gradle.test.RestIntegTestTask

/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

group = 'org.opensearch.knn.plugin'
apply plugin: 'opensearch.opensearchplugin'
apply plugin: 'opensearch.testclusters'
apply plugin: 'opensearch.rest-test'
apply plugin: 'opensearch.pluginzip'

opensearchplugin {
    name = project.name
    description = 'An example plugin implementing brute force k-NN'
    classname = 'org.opensearch.bruteforce.BruteForceEnginePlugin'
    licenseFile = rootProject.file('LICENSE.txt')
    noticeFile = rootProject.file('NOTICE.txt')
    extendedPlugins = ['opensearch-knn']
}

dependencies {
    compileOnly "org.opensearch:opensearch:${opensearch_version}"
    compileOnly project(":enginelib")
    testImplementation "org.opensearch.test:framework:${opensearch_version}"
    testImplementation(testFixtures(rootProject))
}

testClusters.integTest {
    testDistribution = "ARCHIVE"

    plugin(rootProject.tasks.bundlePlugin.archiveFile)
    plugin(project.tasks.bundlePlugin.archiveFile)

}

run {
    useCluster project.testClusters.integTest
}

task integTestRemote(type: RestIntegTestTask) {
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    systemProperty "https", System.getProperty("https")
    systemProperty "user", System.getProperty("user")
    systemProperty "password", System.getProperty("password")

    systemProperty 'cluster.number_of_nodes', "1"

    systemProperty 'tests.security.manager', 'false'
    systemProperty("test.exhaustive", System.getProperty("test.exhaustive"))

    // Run tests with remote cluster only if rest case is defined
    if (System.getProperty("tests.rest.cluster") != null) {
        filter {
            includeTestsMatching "org.opensearch.bruteforce.*IT"
        }
    }
}
